// <auto-generated />
using System;
using ConhecimentoBiblico.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConhecimentoBiblico.Infrastructure.Migrations
{
    [DbContext(typeof(ConhecimentoBiblicoDbContext))]
    [Migration("20260614205418_AdicionarCapitulo4ERelevancia")]
    partial class AdicionarCapitulo4ERelevancia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.ConexaoBiblica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("OrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Relevancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("TipoConexao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigemId");

                    b.ToTable("ConexoesBiblicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1111111-f111-f111-f111-f11111111111"),
                            DestinoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Explicacao = "Jonas ficou 3 dias no ventre do peixe, prefigurando os 3 dias de Jesus no sepulcro e Sua ressurreição.",
                            OrigemId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Relevancia = 9,
                            TipoConexao = 2
                        },
                        new
                        {
                            Id = new Guid("f2222222-f222-f222-f222-f22222222222"),
                            DestinoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Explicacao = "Moisés como mediador da antiga aliança prefigura Cristo, mediador da nova e eterna aliança.",
                            OrigemId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Relevancia = 9,
                            TipoConexao = 2
                        },
                        new
                        {
                            Id = new Guid("f3333333-f333-f333-f333-f33333333333"),
                            DestinoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Explicacao = "O trono eterno prometido a Davi aponta para o reino eterno de Jesus Cristo.",
                            OrigemId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Relevancia = 8,
                            TipoConexao = 1
                        },
                        new
                        {
                            Id = new Guid("f4444444-f444-f444-f444-f44444444444"),
                            DestinoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Explicacao = "Jesus citou Jonas explicitamente ao responder sobre o sinal do Filho do Homem (Mt 12:39-40).",
                            OrigemId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Relevancia = 7,
                            TipoConexao = 6
                        },
                        new
                        {
                            Id = new Guid("f5555555-f555-f555-f555-f55555555555"),
                            DestinoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Explicacao = "Paulo ensina que o casamento é reflexo da relação de Cristo com a Igreja em Efésios 5:25-32.",
                            OrigemId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Relevancia = 7,
                            TipoConexao = 7
                        },
                        new
                        {
                            Id = new Guid("f6666666-f666-f666-f666-f66666666666"),
                            DestinoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Explicacao = "Paulo explica o perdão como graça de Deus em Cristo, exortando os crentes a perdoarem uns aos outros.",
                            OrigemId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Relevancia = 7,
                            TipoConexao = 7
                        },
                        new
                        {
                            Id = new Guid("cb400001-cb40-cb40-cb40-cb4000000001"),
                            DestinoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Explicacao = "Jesus é o protagonista do batismo. É sobre Ele que o Espírito desce e o Pai fala (Mateus 3.16-17).",
                            OrigemId = new Guid("e0400001-e040-e040-e040-e04000000001"),
                            Relevancia = 10,
                            TipoConexao = 13
                        },
                        new
                        {
                            Id = new Guid("cb400002-cb40-cb40-cb40-cb4000000002"),
                            DestinoId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Explicacao = "João Batista administra o batismo de Jesus, cumprindo seu papel de precursor e preparador do caminho (Mateus 3.13-15).",
                            OrigemId = new Guid("e0400001-e040-e040-e040-e04000000001"),
                            Relevancia = 8,
                            TipoConexao = 13
                        },
                        new
                        {
                            Id = new Guid("cb400003-cb40-cb40-cb40-cb4000000003"),
                            DestinoId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Explicacao = "O batismo de Jesus é ato de fé e obediência — cumprimento de toda a justiça (Mateus 3.15).",
                            OrigemId = new Guid("e0400001-e040-e040-e040-e04000000001"),
                            Relevancia = 7,
                            TipoConexao = 12
                        },
                        new
                        {
                            Id = new Guid("cb400004-cb40-cb40-cb40-cb4000000004"),
                            DestinoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Explicacao = "Jesus é levado ao deserto pelo Espírito e enfrenta pessoalmente as tentações do diabo por 40 dias (Mateus 4.1).",
                            OrigemId = new Guid("e0400002-e040-e040-e040-e04000000002"),
                            Relevancia = 10,
                            TipoConexao = 13
                        },
                        new
                        {
                            Id = new Guid("cb400005-cb40-cb40-cb40-cb4000000005"),
                            DestinoId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Explicacao = "A tentação no deserto demonstra que Jesus venceu pela fé na Palavra de Deus, citando as Escrituras em cada resposta (Mateus 4.4, 4.7, 4.10).",
                            OrigemId = new Guid("e0400002-e040-e040-e040-e04000000002"),
                            Relevancia = 8,
                            TipoConexao = 12
                        });
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("ElementoCentral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoElemento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ElementosBiblicos", (string)null);

                    b.HasDiscriminator<int>("TipoElemento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Ensino.PerguntaBiblica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PerguntasBiblicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-e111-e111-e111-e11111111111"),
                            Pergunta = "Por que Jesus citou Jonas?",
                            Titulo = "Jonas e a Ressurreição"
                        },
                        new
                        {
                            Id = new Guid("e2222222-e222-e222-e222-e22222222222"),
                            Pergunta = "O que a Bíblia ensina sobre casamento?",
                            Titulo = "O Que é Casamento?"
                        });
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Ensino.ReflexaoBiblica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AplicacaoPratica")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PerguntaBiblicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerguntaReflexao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaBiblicaId");

                    b.ToTable("ReflexoesBiblicas", (string)null);
                });

            modelBuilder.Entity("PerguntaElementos", b =>
                {
                    b.Property<Guid>("PerguntaBiblicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ElementoBiblicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PerguntaBiblicaId", "ElementoBiblicoId");

                    b.HasIndex("ElementoBiblicoId");

                    b.ToTable("PerguntaElementos");

                    b.HasData(
                        new
                        {
                            PerguntaBiblicaId = new Guid("e1111111-e111-e111-e111-e11111111111"),
                            ElementoBiblicoId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            PerguntaBiblicaId = new Guid("e1111111-e111-e111-e111-e11111111111"),
                            ElementoBiblicoId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            PerguntaBiblicaId = new Guid("e2222222-e222-e222-e222-e22222222222"),
                            ElementoBiblicoId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            PerguntaBiblicaId = new Guid("e2222222-e222-e222-e222-e22222222222"),
                            ElementoBiblicoId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.EventoBiblico", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0400001-e040-e040-e040-e04000000001"),
                            Descricao = "Jesus é batizado por João Batista no Rio Jordão. O Espírito Santo desce sobre Ele como pomba e o Pai declara: 'Este é o meu Filho amado' (Mateus 3.13-17).",
                            ElementoCentral = true,
                            Nome = "Batismo de Jesus",
                            TipoElemento = 3
                        },
                        new
                        {
                            Id = new Guid("e0400002-e040-e040-e040-e04000000002"),
                            Descricao = "Após o batismo, Jesus é levado pelo Espírito ao deserto onde permanece 40 dias e é tentado pelo diabo. Vence cada tentação com as Escrituras (Mateus 4.1-11).",
                            ElementoCentral = true,
                            Nome = "Tentação no Deserto",
                            TipoElemento = 3
                        });
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.LivroBiblico", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.Property<int>("NumeroCaps")
                        .HasColumnType("int");

                    b.Property<int>("Testamento")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.LocalBiblico", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.ParabolaBiblica", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.Property<string>("LicaoCentral")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.PassagemBiblica", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<string>("Livro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TextoResumo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("VersiculoFinal")
                        .HasColumnType("int");

                    b.Property<int>("VersiculoInicial")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.PersonagemBiblico", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.Property<string>("Ocupacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PeriodoHistorico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Descricao = "Filho de Deus, o Messias prometido e cumprimento de todas as profecias.",
                            ElementoCentral = true,
                            Nome = "Jesus",
                            TipoElemento = 1,
                            Ocupacao = "Filho de Deus, Messias",
                            PeriodoHistorico = "Século I d.C."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Descricao = "Apóstolo dos gentios, responsável por explicar a teologia de Cristo.",
                            ElementoCentral = false,
                            Nome = "Paulo",
                            TipoElemento = 1,
                            Ocupacao = "Apóstolo, Teólogo",
                            PeriodoHistorico = "Século I d.C."
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Descricao = "Apóstolo e líder da Igreja primitiva.",
                            ElementoCentral = false,
                            Nome = "Pedro",
                            TipoElemento = 1,
                            Ocupacao = "Apóstolo, Pescador",
                            PeriodoHistorico = "Século I d.C."
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Descricao = "Apóstolo e evangelista, discípulo amado de Jesus.",
                            ElementoCentral = false,
                            Nome = "João",
                            TipoElemento = 1,
                            Ocupacao = "Apóstolo, Evangelista",
                            PeriodoHistorico = "Século I d.C."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Descricao = "Profeta cujos 3 dias no ventre do peixe prefiguram a ressurreição de Cristo.",
                            ElementoCentral = false,
                            Nome = "Jonas",
                            TipoElemento = 1,
                            Ocupacao = "Profeta",
                            PeriodoHistorico = "Século VIII a.C."
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Descricao = "Profeta e legislador, mediador da antiga aliança que prefigura Cristo.",
                            ElementoCentral = false,
                            Nome = "Moisés",
                            TipoElemento = 1,
                            Ocupacao = "Profeta, Legislador",
                            PeriodoHistorico = "Século XIII a.C."
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Descricao = "Rei e salmista, cujo trono eterno aponta para o reinado de Cristo.",
                            ElementoCentral = false,
                            Nome = "Davi",
                            TipoElemento = 1,
                            Ocupacao = "Rei, Salmista",
                            PeriodoHistorico = "Século X a.C."
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Descricao = "Profeta que preparou o caminho do Senhor e batizou Jesus no Rio Jordão (Mateus 3).",
                            ElementoCentral = false,
                            Nome = "João Batista",
                            TipoElemento = 1,
                            Ocupacao = "Profeta, Precursor",
                            PeriodoHistorico = "Século I d.C."
                        });
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.ProfeciaBiblica", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.Property<bool>("Cumprida")
                        .HasColumnType("bit");

                    b.Property<string>("TextoCumprimento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.TemaBiblico", b =>
                {
                    b.HasBaseType("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Descricao = "Confiança e crença em Deus e em Seus propósitos.",
                            ElementoCentral = false,
                            Nome = "Fé",
                            TipoElemento = 2
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Descricao = "União entre homem e mulher que reflete a relação de Cristo e a Igreja.",
                            ElementoCentral = false,
                            Nome = "Casamento",
                            TipoElemento = 2
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Descricao = "A graça de Deus que perdoa os pecados através de Cristo.",
                            ElementoCentral = false,
                            Nome = "Perdão",
                            TipoElemento = 2
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Descricao = "A certeza das promessas de Deus cumpridas em Cristo.",
                            ElementoCentral = false,
                            Nome = "Esperança",
                            TipoElemento = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Descricao = "A redenção do ser humano através do sacrifício de Jesus Cristo.",
                            ElementoCentral = false,
                            Nome = "Salvação",
                            TipoElemento = 2
                        });
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Conhecimento.ConexaoBiblica", b =>
                {
                    b.HasOne("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ConhecimentoBiblico.Domain.Conhecimento.FonteBiblica", "FontesBiblicas", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ConexaoBiblicaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Referencia")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("TextoVersiculo")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("ConexaoBiblicaId");

                            b1.ToTable("ConexaoFontesBiblicas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConexaoBiblicaId");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    ConexaoBiblicaId = new Guid("f1111111-f111-f111-f111-f11111111111"),
                                    Referencia = "Mateus 12:40"
                                },
                                new
                                {
                                    Id = 2,
                                    ConexaoBiblicaId = new Guid("f2222222-f222-f222-f222-f22222222222"),
                                    Referencia = "João 5:46"
                                },
                                new
                                {
                                    Id = 3,
                                    ConexaoBiblicaId = new Guid("f3333333-f333-f333-f333-f33333333333"),
                                    Referencia = "Lucas 20:41-44"
                                },
                                new
                                {
                                    Id = 4,
                                    ConexaoBiblicaId = new Guid("f4444444-f444-f444-f444-f44444444444"),
                                    Referencia = "Mateus 12:39"
                                },
                                new
                                {
                                    Id = 5,
                                    ConexaoBiblicaId = new Guid("f5555555-f555-f555-f555-f55555555555"),
                                    Referencia = "Efésios 5:25-32"
                                },
                                new
                                {
                                    Id = 6,
                                    ConexaoBiblicaId = new Guid("f6666666-f666-f666-f666-f66666666666"),
                                    Referencia = "Efésios 4:32"
                                });
                        });

                    b.Navigation("Destino");

                    b.Navigation("FontesBiblicas");

                    b.Navigation("Origem");
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Ensino.ReflexaoBiblica", b =>
                {
                    b.HasOne("ConhecimentoBiblico.Domain.Ensino.PerguntaBiblica", null)
                        .WithMany("Reflexoes")
                        .HasForeignKey("PerguntaBiblicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerguntaElementos", b =>
                {
                    b.HasOne("ConhecimentoBiblico.Domain.Conhecimento.ElementoBiblico", null)
                        .WithMany()
                        .HasForeignKey("ElementoBiblicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConhecimentoBiblico.Domain.Ensino.PerguntaBiblica", null)
                        .WithMany()
                        .HasForeignKey("PerguntaBiblicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConhecimentoBiblico.Domain.Ensino.PerguntaBiblica", b =>
                {
                    b.Navigation("Reflexoes");
                });
#pragma warning restore 612, 618
        }
    }
}
